version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
    tty: true
    networks:
      - net

networks:
  net:
    driver: bridge
